server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA routing: cualquier ruta que no sea un archivo sirve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
